coiled/benchmarks

LICENSE, continuous_integration/recipe/meta.yaml
=> Update license copyright owner

.github/workflows/conda.yml, .github/workflows/pre-commit.yaml, setup.cfg, tests/test_build.py
I noticed we're current skipping tests in CI. This PR is to make sure those tests are run
cc @ncclementi @hayesgb for visibility
=> Run tests in CI

README.md
=> Document conda-forge requirements in README.md

.github/workflows/conda.yml
Attempt at closing https://github.com/coiled/coiled-runtime/issues/24
EDIT: Closes https://github.com/coiled/coiled-runtime/issues/24
=> Use `mamba` and `boa`

tests/test_coiled.py
Following on from #34 
Closes https://github.com/coiled/coiled-runtime/issues/35
=> Use declarative clusters

.github/workflows/conda.yml
xref https://github.com/coiled/coiled-runtime/pull/40#issuecomment-1098595761
cc @mrocklin
=> Raise a more informative error on test failure

.github/workflows/conda.yml, tests/test_build.py
This probably has problems, and I'm not quite sure how to test it works. But dropping something here to get it started
=> Raise issue when CI on `main` fails

README.md
Specify -c conda-forge in other places in the build
=> Minor documentation nits

.github/workflows/tests.yml, README.md
Just a few small cleanup changes
=> Minor cleanup

.github/workflows/tests.yml
=> Temporarily use conda to export env for debug statement

.github/workflows/tests.yml
Closes https://github.com/coiled/coiled-runtime/issues/71
Closes https://github.com/coiled/coiled-runtime/issues/96
=> Reduce Windows/macOS builds

.github/workflows/tests.yml, ci/create_latest_runtime_meta.py
Closes https://github.com/coiled/coiled-runtime/issues/94
=> Use only `conda` in `upstream` CI build

.github/workflows/tests.yml, conftest.py, tests/test_shuffle.py
Test to see that https://github.com/dask/dask/pull/8982 resolves the issue we were seeing in https://github.com/coiled/coiled-runtime/issues/79
=> Confirm upstream `to_parquet` performance fix

recipe/meta.yaml, tests/test_build.py
Closes https://github.com/coiled/coiled-runtime/issues/75
=> Include packages in Dask version check warning

.github/workflows/software-environments.yml, conftest.py
Closes https://github.com/coiled/coiled-runtime/issues/116
=> Push software environments to `coiled` account

tests/runtime/test_coiled.py
=> Update csv path and add parquet nyc test

.github/workflows/pre-release.yml, .github/workflows/tests.yml, README.md, ci/create_latest_runtime_meta.py, recipe/meta.yaml, tests/runtime/test_build.py
=> Pre release nightly  build and uploads

.github/workflows/tests.yml, recipe/meta.yaml
This PR moves us closer to a new `coiled-runtime` release 
Closes https://github.com/coiled/coiled-runtime/issues/100
=> Upgrade Dask version

.github/workflows/software-environments.yml
Also push coiled-runtime senvs to staging
@jrbourbeau based on what we talked about today this should be enough. I created the account/user pair in staging and added the API token for that user as a secret. Please let me know if I'm missing something
=> Add staging environment

.github/workflows/software-environments-stable.yml, .github/workflows/tests.yml, environments/coiled-runtime-0-0-4-py310.yml, environments/coiled-runtime-0-0-4-py38.yml, environments/coiled-runtime-0-0-4-py39.yml, recipe/meta.yaml
A few updates following the 0.0.4 release 
EDIT: I've reduced the scope of this PR to just create Coiled software environments for the 0.0.4 release. After those exist we can expand the testing matrix to include 0.0.4
=> Create Coiled software environments for 0.0.4 release

tests/stability/test_deadlock.py
See https://github.com/coiled/coiled-runtime/issues/166
=> skip test until distributed PR 6637 is merged

dashboard.py
Example of rendering in the issue.
=> Fix tooltip rendering

.github/workflows/pip-install.yml, ci/environment.yml, pyproject.toml, recipe/meta.yaml, setup.py, tests/runtime/test_build.py
Currently untested. Closes https://github.com/coiled/coiled-runtime/issues/153
cc @dchudz
=> Add `pip`-installable Coiled Runtime

recipe/meta.yaml
=> Add pynvml

dashboard.py
A few small improvements to the dashboard:
* Include the date in the tooltop
* reduce the size of the html file a bit
* if a test has failures, show them as a different marker shape
=> Tweaks to static site

README.md
=> Add pip as installation option

.github/workflows/ab_tests.yml, .github/workflows/tests.yml, AB_environments/README.md, ci/scripts/dask_config_to_env.py, dashboard.py
- Support for branches containing capital letters and special characters
- Also fixes some issues with A/B tests
=> Support for branches containing capital letters and special characters

README.md, conftest.py
=> Add fixture docstrings

conftest.py, tests/benchmarks/test_work_stealing.py, tests/stability/test_deadlock.py, tests/stability/test_spill.py
=> Use t3.xlarge as default schdeduler vm type

.github/workflows/tests.yml, tests/runtime/test_coiled.py
=> Add benchmark for reconnecting to an existing cluster

dashboard.py
I'm only making the time-series plots interactive. I assume we don't need this for the bar charts. Do we?
=> Make dashboard timeseries zoom interactive

.github/workflows/tests.yml, tests/benchmarks/test_join.py
Currently skipping dataframes of sizes 1x and 10x of memory cluster.
=> Add simple test for merges 

dashboard.py
- Fix bug in barcharts where upstream had an incorrect tooltip, showing only 1 run
- Fix bug in A/B charts which caused a crash in case of partially missing data
- Add optional dump of filtered pandas data, for debugging purposes
=> Fix dashboard bugs

.github/workflows/ab_tests.yml, .github/workflows/tests.yml, benchmark_schema.py, conftest.py, tests/benchmarks/test_parquet.py, tests/benchmarks/test_work_stealing.py, tests/runtime/test_cluster_creation.py, tests/stability/test_deadlock.py, tests/stability/test_spill.py
Dump cluster state for all successful runs and dump URI to the database.
=> Always dump cluster state

tests/benchmarks/h2o/test_h2o_benchmarks.py
@jrbourbeau I'm realizing the issue about this was opened in the h2o benchmark. Was that meant to be that way?
=> Add `median`-based h2o queries

alembic/versions/82e8a0855e91_declare_bankruptcy_for_test_futures.py, alembic/versions/fa79471ffa8c_declare_bankruptcy_for_test_futures_py.py, tests/benchmarks/test_futures.py
Make runtime of `test_single_future` and `test_memory_efficient` more stable
=> Stabilize test_future.py

conftest.py
- Closes #486
- Closes #487 (probably)
=> Exclude log_on_scheduler RPC calls from benchmark_time

.github/workflows/software-environments-nightly.yml
Attempting to fix #508 based on https://docs.docker.com/build/ci/github-actions/examples/#multi-platform-images
=> Set up QEMU and Buildx for multiarch docker build

.github/workflows/software-environments-stable.yml, environments/coiled-runtime-0-1-1-py310.yml, environments/coiled-runtime-0-1-1-py38.yml, environments/coiled-runtime-0-1-1-py39.yml
- Adds env files for 0.1.1
Wait until the package is available on conda-forge.
=> Runtime envs for 0.1.1 

tests/benchmarks/test_array.py
The test wasn't doing any computation.
=> Fix `test_sum_residuals`

recipe/meta.yaml, setup.py, tests/runtime/test_build.py
This PR updates the packages for the 0.2.0 release. I was able to conda-build locally, as well as install all the updated packages with a conda env. 
After this PR is merged, I will proceed with the release by bumping the version in the `setup.py` and the following steps for both pypi and conda-forge. 
For the regressions discussions check https://github.com/coiled/coiled-runtime/issues/526
cc: @hayesgb
=> Update packages for release 0.2.0

recipe/meta.yaml
=> Update to `coiled>=0.2.54` for `package_sync` fix

.github/workflows/ab_tests.yml
- Closes #604
Modify set-output usage according to suggestions here https://github.com/orgs/community/discussions/35994
=> Fix GHA set-output deprecation

.github/workflows/tests.yml, AB_environments/AB_baseline.conda.yaml, AB_environments/AB_sample.conda.yaml, dashboard.py, tests/benchmarks/test_array.py
- Closes https://github.com/coiled/coiled-runtime/issues/586
=> Test and process result only for latest, upstream and 0.2.1

.github/workflows/software-environments-stable.yml, environments/coiled-runtime-0-1-0-py38.yml, environments/coiled-runtime-0-1-0-py39.yml, environments/coiled-runtime-0-1-1-py310.yml, environments/coiled-runtime-0-1-1-py39.yml, environments/coiled-runtime-0-2-0-py310.yml, environments/coiled-runtime-0-2-0-py38.yml, environments/coiled-runtime-0-2-1-py310.yml, environments/coiled-runtime-0-2-1-py38.yml, environments/coiled-runtime-0-2-1-py39.yml
- Add environment yaml files for 0.2.1
- Remove stale env.yaml files
- Modify `software-environments-stable.yml` accordingly
cc: @ntabris if you can approve this one, when ci finishes we will merge it.
=> Add envs.yaml for 0.2.1 to create coiled docker images using soft-env-stable workflow

detect_regressions.py
=> Bump std in regressions detection to 3

.github/workflows/pip-install.yml, .github/workflows/tests.yml, recipe/meta.yaml
=> Unskip CI after holidays

alembic/versions/967e298408ed_test_spill.py
Fix merge conflict of #629 and #644
Closes #657
=> Fix merge conflict in alembic

dashboard.py
Recently the automatic datasource has switched to Kobold
=> Explicit Prometheus datasource in Grafana dashboard

tests/conftest.py
This snuck in with #597, removing it again.
=> Remove storing memory samples to CSV

tests/benchmarks/test_h2o.py, tests/conftest.py
Implement dask/dask#10013 in `coiled-runtime` tests
=> Rename shuffle/rechunk config option/kwarg to method

tests/benchmarks/test_join.py
Simplified version of https://github.com/coiled/coiled-runtime/pull/694 that only adds a set_index
=> Add set_index test

dashboard.py
Haven't tested this locally.
1679590932198 is earliest timestamp (in ms, like what Grafana uses) of metrics that went to new datasource.
=> For new test runs use new Grafana URL

ci/environment.yml
xref https://github.com/coiled/coiled-runtime/issues/774#issuecomment-1502332690
=> Add temporary `filelock=3.10.7` pin

AB_environments/README.md
=> Additional troubleshooting for A/B tests

cluster_kwargs.yaml, tests/workflows/test_uber_lyft.py
Exploratory analysis on the NYC Uber/Lyft dataset.
Roughly based on @ncclementi 's dataframe tutorial: https://github.com/coiled/dask-tutorial/blob/main/2-Get_better-at-dask-dataframes.ipynb.
* Xref https://github.com/coiled/coiled-runtime/issues/725.
=> Exploratory DataFrame analysis

README.md
=> Update README.md with working benchmarks link

tests/benchmarks/test_h2o.py
=> Set ``numeric_only`` explicitly to True

AB_environments/README.md
cc @crusaderky 
Based on https://github.com/coiled/benchmarks/issues/808#issuecomment-1532284254
This would have been helpful to me.
=> Add suggestion for an initial repeat value

ci/environment.yml, tests/utils_test.py, tests/workflows/test_pytorch_optuna.py
- Allow test suite to run with a minimal A/B environment
- Don't pollute the environment used by all test with a hard to spot dependency tree introduced in `environment.yml`
- Test timeout
- Add notes on various hacks
=> Polish PyTorch test

.github/workflows/tests.yml, AB_environments/AB_baseline.conda.yaml, AB_environments/AB_sample.conda.yaml, ci/environment.yml
There was a new release of `cryptograph` earlier today that seems to be causing CI to fail on `main` (xref https://cryptography.io/en/latest/changelog/#v41-0-0) with the following error (see [this CI build](https://github.com/coiled/benchmarks/actions/runs/5128188696/jobs/9224620911)):
```python
+ python -m pytest --benchmark -n 4 --dist loadscope tests/stability
ImportError while loading conftest '/home/runner/work/benchmarks/benchmarks/tests/conftest.py'.
tests/conftest.py:20: in <module>
import s3fs
/usr/share/miniconda3/envs/test/lib/python3.10/site-packages/s3fs/__init__.py:1: in <module>
from .core import S3FileSystem, S3File
/usr/share/miniconda3/envs/test/lib/python3.10/site-packages/s3fs/core.py:28: in <module>
import aiobotocore.session …
```
=> Pin `cryptography` / `pyopenssl` to unblock CI 

AB_environments/AB_baseline.conda.yaml, AB_environments/AB_sample.conda.yaml, ci/environment.yml
This contains the performance fix that we want to write about
=> Upgrade pandas to 2.0.2

dashboard.py
These are a couple of QoL changes to how we're setting ranges
- Default view only selects 30days. All data is still there if scrolled
- Set y domain to mean +- stddev
- Scrolling now locks in Y axis. It happens very rarely that we're interested in changing y axis
- Make dots smaller
- Make legend less verbose by not spelling out the test name again, just the parameter
This is still far from ideal but I find it a little easier to work with.
Note: The code is a bit of a mess and I didn't put in a lot of effort to make this very clean. I think `make_test_report` is a bit of an anti pattern since it just redirects to different implementations making the kwarg forwarding very awkward. Topic for another day
Before
After
=> QoL dashboard ranges

AB_environments/AB_baseline.conda.yaml, AB_environments/AB_sample.conda.yaml, ci/environment.yml
we will cut the rc for 2.1 this week, so lets test on 2.0.3 before that happens
=> Upgrade `pandas` version to 2.0.3

cluster_kwargs.yaml, tests/benchmarks/test_join.py
=> Add set_index on uber lyft dataset

tests/workflows/test_pytorch_optuna.py
- https://github.com/coiled/benchmarks/issues/969
FYI @jrbourbeau
=> xfail test_pytorch_optuna.py::test_hpo

ci/environment.yml
closes https://github.com/coiled/benchmarks/issues/990
=> bump pyarrow to 12

tests/benchmarks/test_dataframe.py
=> Fix fillna error in CoW chain

tests/conftest.py
=> Python 3.9-style multi-line with

tests/benchmarks/test_h2o.py
I jumped the gun in https://github.com/coiled/benchmarks/pull/1034 and this is actually broken
=> Remove mark from client fixture

tests/conftest.py
This isn't necessary here, memory usage is not a problem at all
https://github.com/coiled/benchmarks/suites/17093736548/artifacts/976453326
=> Disable task queuing for tpch

tests/benchmarks/tpch/test_dask.py
=> Fix failures from removal of computes

detect_regressions.py
=> Improve messaging around exception for regressions

tests/tpch/conftest.py
Two changes:
1.  Remove the old functools.wraps functionality, now that upstream handles this for us.
2.  Add the module name into the cluster name, so that we can run duckdb and polars simultaneously more easily
=> Update coiled_function decorator

ci/environment.yml, tests/tpch/README.md, tests/tpch/test_pyspark.py
Mostly, but not fully true, mostly because of the following issues:
-  https://github.com/coiled/benchmarks/issues/1114#issuecomment-1771700674
- https://github.com/coiled/platform/pull/3530
- https://github.com/coiled/benchmarks/pull/1083
=> Add README for TPCH

tests/tpch/conftest.py, tests/tpch/test_duckdb.py, tests/tpch/test_polars.py
Previously we had a split system to accommodate the single-machine systems with coiled.function.  Now we make those slightly less convenient in order to clean up the fixture infrastructure.
=> Reorganize fixtures for TPC-H

tests/workflows/test_xgboost_optuna.py
Partially addresses #1140 and others.
Follow-up to #1136
=> Ensure minimum number of trials in `test_xgboost_optuna`

AB_environments/AB_baseline.conda.yaml, AB_environments/AB_sample.conda.yaml, ci/environment-test.yml, ci/environment.yml
=> Realign environments

dashboard.py
=> Make A/B labels more legible

tests/benchmarks/test_dataframe.py
=> xfail test_filter

tests/tpch/test_dask.py
1. create a branch of distributed with an added "assert False" somewhere vital inside shuffle
2. create A/B test where baseline points to that branch; no other AB environments; repeat=1; null_hypothesis=False
3. see what fails
=> Mark tpch tests that use P2P shuffle

tests/tpch/conftest.py
=> Use Cluster.get_spark for pyspark TPC-H tests

tests/workflows/test_pytorch_optuna.py
=> Set index url for GPU pytorch, raise if not using

.github/workflows/ab_tests.yml, tests/conftest.py
Closes https://github.com/coiled/benchmarks/issues/1232
cc @crusaderky
=> Use AB name as cluster tag

.gitignore, tests/benchmarks/test_rechunk.py
Add important use cases to the array rechunk test suite.
- XREF https://github.com/dask/distributed/pull/8330
=> More rechunking tests

tests/workflows/test_pytorch_optuna.py
Will close #1250 and close #1248
=> Fix PyTorch Optuna test

tests/tpch/test_dask.py
This works for both `dask.dataframe` and dask-expr.
=> [TPC-H] Dask query 12

tests/tpch/test_dask.py
---
**NOTE**:
This works using `dask.dataframe` but with dask-expr will fail with:
> RecursionError: maximum recursion depth exceeded
Maybe I should xfail it?
=> [TPC-H] Dask query 9

tests/tpch/test_dask.py
This works with dask.dataframe and dask-expr (0.3.5)
=> [TPC-H] Dask query 10

tests/tpch/test_dask.py
This works for dask.dataframe and dask-expr
=> [TPC-H] Dask query 13

tests/tpch/test_dask.py
This works for both dask.dataframe and dask-expr.
=> [TPC-H] Dask query 14

tests/tpch/test_correctness.py, tests/tpch/test_dask.py
=> [TPC-H] Fix query 12 correctness

tests/tpch/test_correctness.py, tests/tpch/test_dask.py
Works with dask.dataframe and dask-expr.
=> [TPC-H] Dask query 17

tests/tpch/test_correctness.py, tests/tpch/test_dask.py
Works with `dask.dataframe`  and dask-expr
=> [TPC-H] Dask query 11

tests/tpch/test_correctness.py, tests/tpch/test_dask.py
Works with dask.dataframe and dask-expr.
=> [TPC-H] Dask query 18

tests/tpch/test_correctness.py, tests/tpch/test_dask.py
=> [TPC-H] Dask query 19

tests/tpch/test_correctness.py, tests/tpch/test_optimization.py
Closes #1325 
Blocked by and includes #1324
=> Benchmark plan generation and optimization on TPC-H queries

.github/workflows/tests.yml
=> Minor: Adjust conflict for TPC-H query execution

tests/tpch/test_dask.py
Should address https://github.com/coiled/benchmarks/issues/1337#issuecomment-1923757050
=> [TPC-H] Don't return from tests

.github/workflows/tests.yml
Follow-up to https://github.com/coiled/benchmarks/pull/1349#discussion_r1478525854
=> Reset execution schedule

tests/tpch/conftest.py, tests/tpch/test_correctness.py, tests/tpch/utils.py
Avoid issues on CI for `test_correctness` by using a Coiled cluster
=> Use Coiled cluster on CI for `test_correctness`

tests/workflows/test_snowflake.py
=> Skip test_snowflake until fixed

tests/tpch/test_polars.py
=> Use scan_parquet over scan_dataset for polars

alembic/versions/25053f75e09f_add_dask_expr_version_tracking_migration.py, benchmark_schema.py, tests/conftest.py
=> Add dask-expr version tracking in db

ci/environment-tpch-nondask.yml
=> Bump Polars to `0.20.10`

.github/workflows/tests.yml, ci/environment-test.yml
=> Use pip for duckdb install until #1418 closed

.github/workflows/tests.yml, AB_environments/AB_baseline.dask.yaml, AB_environments/AB_sample.dask.yaml, ci/environment-git-tip.yml, tests/tpch/dask_queries.py, tests/tpch/test_dask.py
=> Enable dask-expr in benchmarks

ci/environment-tpch-nondask.yml
Were some serious issues resolved around new string type and parquet files upstream. 
ref https://github.com/coiled/benchmarks/issues/1396
=> Update polars `0.20.13`

.github/workflows/tpch.yml
Fixes https://github.com/coiled/benchmarks/actions/runs/8235051302/job/22518272712#step:12:122
=> Fix TPC-H trigger

tests/tpch/conftest.py, tests/tpch/generate_data.py, tests/tpch/utils.py
=> [TPC-H] Move utility functions to `utils.py`

tests/tpch/dask_queries.py
I was reviewing the implementation for Q17 and was a little surprised. This is actually a pretty heavy query that, in it's current form, requires us to shuffle lineitems multiple times.
However, if I take the sql in the doc string literally, I should only be required to compute this on a filtered linetime (namely, the one after the join, i.e. where `l_partkey = p_partkey`).
There is a caveat with this... it looks like the optimizer is either never converging or is just taking ages. Even for a scale1 dataset this is simplifying forever
=> Rewrite q17

tests/tpch/duckdb_queries.py, tests/tpch/test_duckdb.py
=> [TPC-H] Move DuckDB queries to their own module

tests/tpch/dask_queries.py
This adopts the polars order and gives us a nice improvement
=> Improve merge ordering for query 18

tests/tpch/conftest.py
See https://github.com/coiled/benchmarks/issues/1430 in case we don't go through with https://github.com/dask-contrib/dask-expr/issues/918 for whatever reason
=> enable COW for tpch

tests/tpch/dask_queries.py, tests/tpch/generate_answers.py, tests/tpch/test_correctness.py, tests/tpch/utils.py
Closes #1443
~For some reason, Q15 at SF 100 and 100 is off. The DuckDB result appears to be empty, which I assume to be wrong.~ The problem with Q15 has been fixed by #1454.
=> Test TPC-H correctness on more scale factors

tests/tpch/conftest.py
=> Track changes in Spark executors between queries

.github/workflows/tpch.yml
Copy+paste is hard if you can't validate.
=> Fix TPC-H workflow (2/2)

tests/tpch/conftest.py
Close #1449 
Default raise when Spark executor count changes during fixture use, with option to downgrade to a warning: `--ignore-spark-executor-count`.
=> [TPC-H] Default raise on Spark executor count change

AB_environments/README.md, AB_environments/make_envs.py
Automate creation of A/B config files
=> A/B make_envs utility

ci/requirements-2tpch-non-dask.in, tests/tpch/conftest.py
Fixes OOM problems that led to inconsistent TPC-H benchmarks.
=> Fix memory issues for Spark

tests/tpch/plot_results.ipynb, tests/tpch/plotting.py
=> Utilities for plotting TPC-H results

tests/tpch/dask_queries.py
Fixes memory pressure at SF 10000
=> Add split_out for Q15

ci/requirements-1general-deps.in, ci/requirements-1tpch-non-dask.in
Closes https://github.com/coiled/dask-engineering/issues/251
=> Don't use coiled pre-releases

ci/environment.yml, tests/tpch/generate_data.py
This always returned 96 previously, leading to useless results and huge partitions
=> Fix file size determination for data generation script

tests/tpch/dask_queries.py
This gets rid of a few manual optimisations. We run into issues if we do the isin after the merge (they are on my todo list to fix, but not sure when I get to it)
=> Remove unnecessary maunual optimizations

.github/workflows/tpch.yml
=> Enable SF 10,000 in Github Actions

tests/tpch/test_polars.py
We received some feedback that the streaming API is not the recommended way of running things and we should rather be running it in the normal mode
cc @ritchie46
=> [TPCH] Polars turn off streaming

.github/workflows/tests.yml, tests/stability/test_install_plugins.py
=> Add stability test for private pip install

ci/scripts/combine-dbs.sh
=> Avoid duplicate data in `benchmark.db`

tests/tpch/test_optimization.py
XREF: https://github.com/dask/distributed/issues/8833
=> Disable broken `test_delay_computation_start`

tests/benchmarks/test_array.py, tests/benchmarks/test_xarray.py
=> Move xarray tests into a single file

tests/geospatial/test_climatology.py
=> Fix output chunks

tests/conftest.py
=> Fix geospatial benchmarks without --benchmark

ci/environment.yml, tests/geospatial/test_zonal_average.py
See https://github.com/rasterio/rasterio/issues/3232 for more context
=> Change rasterio opening call to new recommended method

.github/workflows/ab_tests.yml, .github/workflows/geospatial.yml, .github/workflows/tests.yml, tests/conftest.py, tests/geospatial/conftest.py
Addresses https://github.com/coiled/benchmarks/actions/runs/11800020434/job/32869942751#step:13:31
=> Fix CI (1/n)

AB_environments/AB_baseline.conda.yaml, AB_environments/AB_sample.conda.yaml, ci/environment.yml
=> Update CI environment
