coiled/benchmarks

continuous_integration/recipe/meta.yaml
Based on the `dask` nightly conda build `meta.yaml` files, I don't think this SHA is needed (I'm also not sure where it came from originally). If CI passes here, let's remove it
=> Remove unneeded SHA from conda recipe

.github/workflows/conda.yml
This matches what's used over in `distributed` and, I think, might fix some of the GHA job cancellation issues were were seeing earlier (xref https://github.com/coiled/coiled-runtime/pull/19#discussion_r846298772) 
cc @ncclementi 
EDIT: See https://docs.github.com/en/github-ae@latest/actions/learn-github-actions/contexts#github-context for the difference between `github.head_ref` and `github.ref`
=> Update GitHub actions cancelling condition

.github/workflows/conda.yml, ci/create_latest_runtime_meta.py, conftest.py, setup.cfg, tests/test_build.py, tests/test_coiled.py
This adds the logic necessary for us to run our existing CI builds against multiple coiled-runtime versions. This way we can make sure that any tests, benchmarks, etc. which are added here run against the latest coiled-runtime version (i.e. whatever is in the main branch of this repo) as well as all currently support coiled-runtime releases.
Supersedes https://github.com/coiled/coiled-runtime/pull/27
=> Test multiple runtimes

.github/workflows/conda.yml, tests/test_build.py
Currently we're setting `continue-on-error: true` for our testing step so we can make sure we delete any Coiled software environments we created as part of a push to `main` or a PR. However, since we only ever create Coiled software environments on the latest build, we should only set `continue-on-error: true` on latest builds. Otherwise, we end up with tests failing and a green check mark for the GHA build. 
Closes https://github.com/coiled/coiled-runtime/issues/42
=> Make sure when tests fail CI jobs always fail

.github/workflows/conda.yml, conftest.py, recipe/meta.yaml
The currently pinned versions of `dask` / `distributed` support Python 3.7 and the latest `coiled` release also supports Python 3.7. Seeing what it would look like to add Python 3.7 to `coiled-runtime`
cc @ntabris
=> Add Python 3.7

recipe/meta.yaml, tests/test_build.py
Updating this `click` pinning leads to me getting the latest `coiled==0.0.73` release when I build `coiled-runtime` locally and then attempt to install it. We need this `click` pin as `click=8.1.0` broke `distributed`. We've since included a fix in `distributed` itself (xref https://github.com/dask/distributed/pull/6018), but we can't use that version of `distributed` as it has known stability issues. 
TODO:
Closes https://github.com/coiled/coiled-runtime/issues/22
=> Solve with latest `coiled` release

conftest.py
I hadn't realized how frequently we'd run into errors with using non-declarative Coiled cluster (good job declarative team!). Now that we're pulling in the latest `coiled` by default, let's just switch back to only using new v2 clusters
xref https://github.com/coiled/coiled-runtime/issues/60
cc @dchudz
=> Declarative clusters only 

recipe/meta.yaml
Versions were selected to be the most recent releases that still support Python 3.7
Closes https://github.com/coiled/coiled-runtime/issues/56
=> Add `xarray` and `zarr`

.github/workflows/conda.yml
We want the software environment to be different for pushes. This PR also makes the names a bit more compact
Closes https://github.com/coiled/coiled-runtime/issues/63
=> Make Coiled software environment name more robust in CI

.github/workflows/tests.yml
These builds should hopefully pass now after https://github.com/conda-forge/coiled-feedstock/pull/89
cc @ncclementi 
Closes https://github.com/coiled/coiled-runtime/issues/49
=> Unskip Windows CI builds

.github/workflows/tests.yml, conftest.py, recipe/meta.yaml, tests/test_shuffle.py
Increase dataframe size to ~80GB. Introduce:
1. Read Operations
2. Shuffle
3. Write operations
Prior to this, it would be nice to able to write the ~80GB to some temporary AWS location that gets cleaned up once the tests complete. The written data should also be cleaned up after the tests complete.
=> Larger dataframe shuffle

.github/workflows/tests.yml, README.md, ci/create_latest_runtime_meta.py, conftest.py, environments/coiled-runtime-0-0-3-py37.yml, environments/coiled-runtime-0-0-3-py38.yml, environments/coiled-runtime-0-0-3-py39.yml, tests/test_coiled.py
Since `coiled-runtime` is on `conda-forge` now, we no longer need to specify `-c coiled`
=> Drop `coiled` conda channel

.github/workflows/tests.yml, README.md
This PR updates our release procedure to reflect that we're now issuing releases on conda-forge (instead of the `coiled` conda channel) as well as adds a few more details. 
cc @ncclementi @fjetter @hayesgb
=> Update release procedure

.github/workflows/tests.yml, ci/create_latest_runtime_meta.py, tests/test_build.py
This PR makes it so when a commit message on a PR contains the phrase `test-upstream`, we use the current `main` branch version of `dask` and `distributed` in the `latest` CI build 
Closes https://github.com/coiled/coiled-runtime/issues/89
=> Test against development version of `dask` and `distributed`

.github/workflows/tests.yml
Should fix 
```
fatal: ambiguous argument 'HEAD^2': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```
that we're seeing in [CI builds on `main`](https://github.com/coiled/coiled-runtime/runs/6276096609?check_suite_focus=true) following https://github.com/coiled/coiled-runtime/pull/91
=> Fix commit parsing on non-PRs

.github/workflows/tests.yml
Now when there's a CI failure on `main` (whether a push to `main` or a scheduled cron job) a new issue will always be opened 
Closes https://github.com/coiled/coiled-runtime/issues/103
=> Always alert for CI failures on main

conftest.py, setup.cfg, tests/stability/conftest.py
This PR updates our stability tests to automatically use spot instances by default. This will make sure we're resilient to workers randomly leaving the cluster. 
Closes https://github.com/coiled/coiled-runtime/issues/122
EDIT: This also has a small cost-savings benefit, but my main motivation for this change is making sure our stability tests are robust when workers go offline
=> Use spot instances in stability tests

README.md
Minor follow-up from previous work which consolidated development dependencies into a conda environment file
=> Point to environment file in testing docs

conftest.py
=> Remove `worker_memory` and use t3.large on `Cluster` creation

.github/workflows/tests.yml
The correct job name is `benchmarks` not `benchmarking`
Closes https://github.com/coiled/coiled-runtime/issues/160
=> Fix test report

tests/benchmarks/test_parquet.py
This is the start of some parquet-related integration tests running against open data on AWS. They constitute a "large data" (10s of GiB) test against two different partitioning schemes.
TODO:
=> Parquet tests on AWS open datasets

tests/runtime/test_coiled.py
To avoid cross-region data accessing costs, I copied over data needed to the S3 ci-runtime bucket. This PR has the changes to use the copied data instead.
=> Use cp of nyc taxi data in pour ci bucket to avoid cross region

.github/workflows/software-environments-stable.yml
In https://github.com/coiled/coiled-runtime/pull/180, I didn't account for `coiled-runtime=0.0.4` supporting Python 3.8 - 3.10, while `coiled-runtime=0.0.3` supports Python 3.7 - 3.9. This PR makes sure we have the correct runtime / Python version combinations
=> Handle Python version combinations when creating Coiled software environments 

conftest.py
Currently, when we go through the path in line 177 we raise, causing the last piece of code not to run. This PR fixes the problem
https://github.com/coiled/coiled-runtime/blob/45bc8e9efa852fcf84c5a78289691157f48fc15e/conftest.py#L168-L194
=> Fix cluster dump loggic when raise occurs

.github/workflows/tests.yml
Currently, we are not the tests for 0.0.4, this PR includes these cases. This will make CI much longer, I wonder to what extent we need to keep running the tests in 0.0.3. 
Opinions? 
cc: @hayesgb and @ian-r-rose
=> Add runn tests for 0.0.4 

recipe/meta.yaml
From now on we will use semantic versioning.  For the next release we will use 0.1.0
This targets  #194 and #133 
I don't want to automatically close the issues until we see this in action (next release) but want to make it visible.
cc: @ian-r-rose for visibility
=> Start using semantic versioning

.github/workflows/tests.yml
The last step of this was skipped in the scheduled run yesterday, seemingly because of an upstream job failure (even though its actual dependency was successful). See [this SO](https://stackoverflow.com/questions/65735099/github-workflow-job-not-executed-even-when-job-needs-successful) discussion.
=> Generate dashboard more insistently

conftest.py
There are other ways to get AWS credentials than environment vars, which boto will handle fine. This is annoying when running tests locally.
=> Don't require AWS env vars to be set

.github/workflows/tests.yml, ci/condarc
We've been observing some CI failures in `main` due to conda download timeouts. This PR increases related timeouts and retries (similar to what we're doing in `distributed`) to hopefully be more robust to these types of failures
=> Make CI more robust to transient conda setup failures

ci/condarc
Attempt at fixing #236.  Strict priority seemingly doesn't work for direct URLs to nightly conda builds
=> Remove strict priority

conftest.py, tests/benchmarks/test_coiled.py, tests/benchmarks/test_parquet.py, tests/runtime/test_build.py, tests/stability/test_deadlock.py
Fixes #238 
Create a `benchmark_time` contextmanager fixture for more granular benchmarking of tests when desired. The old behavior is available through `auto_benchmark_time`. The fixture is no longer autoused throughout the whole test suite to allow for custom usage, though I have applied it to `small_client` and `parquet_client` so those should continue working.
=> More specific time benchmarking

.github/workflows/tests.yml
This should make sure our `ci-failure` label is automatically applied when an upstream test failure issue is opened
=> Add `ci-failure` label to upstream report

ci/environment-dashboard.yml, dashboard.py
Handle BaseExceptions in dashboard generation, include xgboost and dask-ml in dashboard env
Fixes #244. No matter how careful you think you are being, somebody comes along and inherits from `BaseException`.
=> Fix static site gen

tests/stability/test_spill.py
=> Integration tests for spilling

recipe/meta.yaml, setup.py
Updates package versions for releasing 
xref https://github.com/coiled/coiled-runtime/issues/233
=> Release 0.1.0

.github/workflows/software-environments-stable.yml, environments/coiled-runtime-0-1-0-py310.yml, environments/coiled-runtime-0-1-0-py38.yml, environments/coiled-runtime-0-1-0-py39.yml
Creates new Coiled software environments that use the fresh `coiled-runtime=0.1.0` release
=> Build `coiled-runtime=0.1.0` software environments

conftest.py, tests/benchmarks/test_work_stealing.py
=> Tests for work stealing

conftest.py
=> Fix `benchmark_task_durations` fixture when running without `--benchmark` option

README.md, alembic/versions/924e9b1430e1_spark_test_bankruptcy.py, tests/benchmarks/test_parquet.py
This was a silly mistake on my part due to not updating a path when the data location changed. But I'm using this as an opportunity to document how one might delete old, irrelevant data.
=> Fix spark flavored parquet test

tests/benchmarks/test_array.py
Temporary workaround until https://github.com/dask/dask/issues/9488 is fixed upstream.
Maybe a fix for https://github.com/coiled/coiled-runtime/issues/316, https://github.com/coiled/coiled-runtime/issues/315, https://github.com/coiled/coiled-runtime/issues/299?
=> Remove size literals from `chunks=`

.github/workflows/tests.yml, README.md, alembic/versions/2764a4f5582b_declare_bankruptcy_for_cluster_startup_.py, ci/create_runtime_meta.py, ci/scripts/combine-dbs.sh, ci/scripts/install_coiled_runtime.sh, ci/scripts/run_tests.sh, conftest.py, tests/benchmarks/test_coiled.py, tests/benchmarks/test_parquet.py, tests/runtime/test_build.py, tests/stability/test_deadlock.py, tests/stability/test_shuffle.py, tests/stability/test_spill.py
Pushing #222 a bit further to see if anything breaks. This
1. Removes a couple of controlling environment variables, which should simplify local development as well as CI workflows. Specifically `TEST_UPSTREAM` has been folded into `COILED_RUNTIME_VERSION`, which can be a version number, "upstream", or "latest", and `COILED_SOFTWARE_VERSION` is no longer necessary in a `package_sync` universe.
2. Removes the setup/cleanup jobs. This also means there are fewer artifacts passed around between jobs, which is nice.
3. "upstream" is now run on pull requests
=> Package Sync

AB_environments/AB_sample.dask.yaml.rename_me
I think it's easy to forget about this if you only care about a commit but not any config changes. Already happened over in https://github.com/dask/distributed/pull/7024
Let's keep it as an example
=> Comment out worker-saturation in AB_sample.dask

tests/benchmarks/test_work_stealing.py
Let's try un`skip`ping `test_work_stealing_on_scaling_up` since a possible fix has been deployed on Coiled (xref https://github.com/coiled/coiled-runtime/issues/336#issuecomment-1249955112) 
Closes https://github.com/coiled/coiled-runtime/issues/336
=> Unskip `test_work_stealing_on_scaling_up`

tests/benchmarks/test_work_stealing.py
- Work around https://github.com/coiled/platform/issues/103
=> Workers may not be online when Cluster(wait_for_workers=True) returns

ci/environment-dashboard.yml
altair 4.2.0 + pandas 1.5.0 produce a ton of DeprecationWarnings
=> Block upgrade to pandas 1.5.0

tests/runtime/test_cluster_creation.py, tests/runtime/test_coiled.py
Follow-up from https://github.com/coiled/coiled-runtime/pull/341
=> Move `test_default_cluster_spinup_time` to its own module

.github/workflows/ab_tests.yml, .github/workflows/tests.yml, AB_environments/config.yaml, ci/scripts/discover_ab_environments.py, ci/scripts/run_tests.sh
Use pytest-xdist to parallelize [stability, runtime, benchmarks] instead of github actions.
Closes #279
=> Use single job for all test categories

.github/workflows/ab_tests.yml
Reduce maximum number of clusters created at the same time for each A/B test suite from 140 to 35.
Note that this does not put a cap on the absolute maximum number of parallel runs; if multiple A/B branches are pushed at the same time, there are going to be 35 coiled clusters spun up for each branch.
=> Reduce A/B parallelism

tests/benchmarks/test_csv.py, tests/runtime/test_coiled.py
These are no longer used as the quickstart on cloud.coiled.io. Let's keep the csv example so we can continue to monitor `read_csv` performance. We have other `read_parquet` benchmarks that capture the parquet version of the old quickstart, so we can just remove that one.
=> Remove quickstart examples

tests/benchmarks/test_work_stealing.py
We're currently seeing package mismatches in CI as `package_sync` isn't being used 
cc @hendrikmakait @crusaderky 
cc @shughes-uk in case you have time to add a `package_sync` config value
=> Use `package_sync` in `test_work_stealing_on_straggling_worker`

README.md
cc @hayesgb, who expressed some interest in this
=> Document a workflow for investigating performance regressions.

conftest.py, tests/benchmarks/test_parquet.py, tests/benchmarks/test_work_stealing.py, tests/stability/test_deadlock.py, tests/stability/test_spill.py
I'd like to collect metrics from at least one CI run.
Maybe we want to do this for every CI run, but we should at least check the cost first.
=> Set backend option to send prometheus metrics

recipe/meta.yaml
This PR updates `numba` to the latest release `0.56.3`. This fixes installation problems when using `pip install .` to install the metapackage dependencies on an Apple M1 as prescribed in https://github.com/coiled/coiled-runtime/blob/595c449f9a8c55ffe23d64c639314c46a4db1540/README.md#create-your-software-environment.
Native installation support for `numba` using `pip` on an Apple M1 has been added in `0.55.2` (https://github.com/numba/numba/releases/tag/0.55.2), so in case something breaks due to the minor version upgrade, we could use that one instead.
=> Update `numba` for M1 support

conftest.py
This PR adds a cluster restart to teardown to avoid that failures/side-effects spill over into setup of subsequent tests.
=> Restart cluster during teardown to avoid failures spilling over

conftest.py
This PR logs when we start/finish setup/teardown of the `small_client` fixture on the scheduler. This helps to correlate cluster logs with issues. We have seen some CI failures in the cluster (e.g. #441) where being able to pinpoint when these phases happen would have facilitated debugging.
Merge conflicts with:
* #472
=> Log `small_client` fixture phases on the scheduler

tests/benchmarks/test_array.py
This PR persists the data accessed in `test_access_slices` on the cluster instead of moving it to the client (and dropping it right after). This reduces the memory footprint of the client since the accessed slice takes up ~2.5 GB for `N==700`. This should solve the problem with `pytest-xdist` workers dying.
**Explanation**
This solution is based on theory and trying the change on CI, not any useful information gathered from CI errors. All I can tell is that the `pytest-xdist` workers are dying _for some reason_ with
```
[gw0] linux -- Python 3.9.13 /usr/share/miniconda3/envs/test/bin/python
worker 'gw0' crashed while running 'tests/benchmarks/test_array.py::test_access_slices[700]'
```
Running `test_access_slices` locally with `.compute()` led to the client process starting to eat up a …
=> Fix `test_access_slices`

recipe/meta.yaml
This adds upgrades dask and distributed to `2022.10.2`.
Note that pyarrow is still at `9.0.0` as v10 is not yet on `conda-forge`
=> Upgrades latest to dask==2022.10.2

.github/workflows/software-environments-nightly.yml
Unless this breaks something (or drastically increases build time?) I'd like us to build both x86 and arm docker images. This would make it much easier to use `coiled-runtime` on Coiled with ARM instances.
=> Build docker images for ARM (+x86)

.github/workflows/software-environments-stable.yml
This is working on the nightlies... x86 and arm images are both available at https://hub.docker.com/r/coiled/coiled-runtime/tags?page=1&name=nightly-0.2.0a2211110032-py3
And they work on Coiled with Graviton instances:
```python
import coiled
coiled.create_software_environment(
name='nightly-py310',
container='coiled/coiled-runtime:nightly-0.2.0a2211110032-py3.10'
)
cluster = coiled.Cluster(
software='nightly-py310',
scheduler_vm_types=['t4g.large'],
worker_vm_types=['t4g.large']
)
```
So let's build the stable released for ARM.
=> Build (stable) docker image for ARM (+x86)

tests/runtime/test_cluster_creation.py
Currently we're using the default number of workers (i.e. 4) for measuring how fast a cluster spins up. This PR proposes we only spin up a single worker. This will, I think, provide the same rough time estimate we're after, while using fewer AWS resources. 
cc @ntabris
=> Use a single worker for cluster spinup time

.pre-commit-config.yaml, conftest.py
Explanation why this bypasses the race condition in the comment. See also https://github.com/dask/distributed/issues/7312
Closes https://github.com/coiled/coiled-runtime/issues/468
=> Ensure concurrent restarts are not interfering

tests/benchmarks/test_parquet.py, tests/stability/conftest.py, tests/stability/test_spill.py
Fixes #507
(I also removed backend_option to send prometheus metrics since I now have that set at account-level for `dask-engineering` account.)
=> Use spot + fallback + multizone for all clusters

recipe/meta.yaml, setup.py, tests/runtime/test_build.py
see https://github.com/coiled/coiled-runtime/issues/530
@jrbourbeau this should be a quick review.
=> Pin bokeh and coiled for 0.1.1 release

.github/workflows/tests.yml, tests/stability/test_array.py
Reverts only changes in `test.yml` introduced in coiled/coiled-runtime#443
=> Revert "OLS Workload" fix ci debugging code. 

recipe/meta.yaml, setup.py
Finally, pyarrow 10.0.1 is available on conda-forge. Partially covers: #582
This PR pins pyarrow version and bumps setu.py for patch release. 
cc: @hayesgb
=> Patch release: Bump pyarrow to 10.0.1

README.md, conftest.py, tests/runtime/test_cluster_creation.py, tests/runtime/test_coiled.py
- Measure cluster reconnect time. The test already existed but it was not recording anything.
- Remove auto_benchmark_time fixture, as it was sensitive to ordering issues with other fixtures
=> Measure cluster connect time

conftest.py
Ran into an error like
```
@pytest.fixture(scope="session")
def cluster_kwargs() -> dict:
base_dir = os.path.dirname(__file__)
base_fname = os.path.join(base_dir, "cluster_kwargs.yaml")
with open(base_fname) as fh:
config = yaml.safe_load(fh)
override_fname = os.getenv("CLUSTER_KWARGS")
if override_fname:
override_fname = os.path.join(base_dir, override_fname)
with open(override_fname) as fh:
override_config = yaml.safe_load(fh)
>           dask.config.update(config, override_config)
conftest.py:437: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
old = {'default': {'backend_options': {'multizone': True, 'send_prometheus_metrics': True, 'spot': True, 'spot_on_demand_fal...pes': ['m6i.large']}, 'spill_cluster': {'n_workers': 5, 'worker_disk_size': 64, …
```
=> Handle the case of empty cluster overrides

tests/benchmarks/h2o/test_h2o_benchmarks.py, tests/benchmarks/test_array.py, tests/benchmarks/test_csv.py, tests/benchmarks/test_futures.py, tests/benchmarks/test_join.py, tests/benchmarks/test_parquet.py, tests/benchmarks/test_work_stealing.py, tests/benchmarks/test_zarr.py, tests/conftest.py, tests/test_utils_test.py, tests/utils_test.py
Partially closes #483 
Review all tests so that they retain a pseudo-constant runtime as the cluster size goes up. Disable those that can't for very large clusters.
Demo with 2x[1] and 5x[2] cluster sizes:
https://github.com/coiled/coiled-runtime/actions/runs/3584320320
[1] 20 workers on small_cluster, 30 workers on parquet_cluster
[2] 50 workers on small_cluster, 75 workers on parquet_cluster
=> Scale tests with cluster size

cluster_kwargs.yaml
Let's use small scheduler since that doesn't appear to impact perf.
(IIRC we switched from large to xlarge back when we were using t3's, I wouldn't be surprised if it did matter for those.)
=> Switch scheduler to m6i.large (2 vCPU) from m6i.xlarge (4 vCPU)

.github/workflows/pip-install.yml, .github/workflows/tests.yml
- This is to avoid CI failure issues opened by GHA. 
- Revert changes on January 3rd 2023
=> Skip CI during holidays

recipe/meta.yaml, tests/benchmarks/test_xgboost.py, tests/conftest.py, tests/utils_test.py
This replicates notebooks "Feature engineering" and "Modelling 2" from https://github.com/coiled/dask-xgboost-nyctaxi, with the exception that it doesn't shuffle around the training and test splits (it would have slown down the test 5x and it wouldn't have been very interesting from a dask point of view).
=>  Test integration with xgboost and optuna

tests/benchmarks/test_parquet.py, tests/benchmarks/test_spill.py, tests/benchmarks/test_work_stealing.py, tests/conftest.py, tests/runtime/test_cluster_creation.py, tests/stability/test_deadlock.py
Just a minor cosmetic change from `gitlab_cluster_tags` --> `github_cluster_tags`, given the tags here are all pulled from GitHub Actions environment variables
=> Update CI cluster tag variable name

recipe/meta.yaml
This fixes a very tedious warning when calling `xgboost.dask.train`.
=> Bump xgboost to 1.7.4

.github/workflows/tests.yml
This is an incremental change related to https://github.com/coiled/coiled-runtime/issues/732
=> Don't test against 0.2.1 runtime release

tests/benchmarks/test_parquet.py
#565 accidentally disabled two parquet tests (the default parquet cluster size is 60 threads)
=> Re-enable two parquet tests

tests/runtime/test_build.py
Fix e.g.
https://github.com/coiled/coiled-runtime/actions/runs/4617936173/jobs/8164769127?pr=746
AssertionError: assert <Version('0.5.10')> == <Version('0.5.9')>
=> Fix failure in 'pip installation' CI every time there's a new release

tests/runtime/test_build.py
This PR `xfails` this test as it's flaky and fixing it will require reworking our CI install infrastructure (which we'll want to do at some point anyways). We could also drop this test altogether, but I do think there's some value in making sure we're always testing against the latest version of `coiled`. 
xref https://github.com/coiled/benchmarks/issues/788
=> `xfail` `test_latest_coiled`

cluster_kwargs.yaml
`m6i.xlarge` is now our default instance type, so we should need to specify these `worker_vm_types` anymore 
cc @ntabris
=> Add context when using default worker instance type

AB_environments/AB_baseline.conda.yaml, AB_environments/AB_sample.conda.yaml, AB_environments/README.md, recipe/meta.yaml
Avoids unnecessary deep-copy when unspilling uncompressed numpy arrays (dask/zict#74)
=> Upgrade to zict 3.0

cluster_kwargs.yaml, tests/conftest.py, tests/workflows/test_embarrassingly_parallel.py, tests/workflows/test_uber_lyft.py, tests/workflows/test_xgboost_optuna.py
Currently there's quite a bit of boilerplate code that's getting copy-pasted in each workflow module. This PR moves that code into a pytest marker + fixture for reuse / a more pleasant interface. 
Steps here are to:
1. Add named cluster spec to `cluster_kwargs.yaml`
2. Mark test with `@pytest.mark.client(<spec-name>)`
3. Add the `client` fixture to the test (the materialized `client` will be attached to a cluster with the given spec)
This seems like a decent improvement to me
=> Add pytest marker/fixture for client creation

.github/workflows/ab_tests.yml, .github/workflows/tests.yml, .gitignore, ci/scripts/install_coiled_runtime.sh, cluster_kwargs.yaml, tests/benchmarks/test_parquet.py, tests/benchmarks/test_spill.py, tests/conftest.py, tests/workflows/test_embarrassingly_parallel.py, tests/workflows/test_uber_lyft.py
Dump all kwargs passed to `coiled.Cluster`, as well as the output of `mamba env export`, to the github artifacts. This can be useful to debug issues.
XREF #756
=> Dump extra info in github artifacts

ci/environment-dashboard.yml
Fixes
```
python dashboard.py -d benchmark.db -o static -b coiled-AB_baseline-py$PY_VER
Could not import tests/benchmarks/test_zarr.py: Skipped: could not import 'zarr': No module named 'zarr'
Could not import tests/workflows/test_xgboost_optuna.py: Skipped: could not import 'optuna': No module named 'optuna'
```
=> Parse zarr and xgboost tests

.github/workflows/ab_tests.yml
Fix interaction of #716 + #746 which caused the A/B dashboard not to have the confidence intervals
=> Fix confidence intervals plot in A/B dashboard

tests/benchmarks/test_join.py
This test is very noisy and really doesn't add anything to test_join_big_small[1].
Note also how test_join_big_small[1] doesn't spill - which would be one thing that would make it different.
A/B test on 7 runs vs. null hypothesis:
Note how the end-to-end runtime is heavily cluster-driven: the four tests run one after another on the same cluster and you can see that, given the same cluster, they have exactly the same end-to-end runtime minus a fixed offset.
=> Disable test_join_big_small[0.1]

cluster_kwargs.yaml
Follow-up to #787 pinning the VM type as AWS would otherwise vary this between runs. See https://coiledcomputing.slack.com/archives/C018NCJG8LX/p1685449020103739 (Coiled only)
=> Pin GPU VM type for Pytorch + Optuna GPU workload

AB_environments/AB_baseline.conda.yaml, AB_environments/AB_sample.conda.yaml, ci/environment.yml
`optuna=3.2.0` is out now, so we should be able to use that instead of installing from GitHub
=> Use `optuna=3.2.0`

tests/benchmarks/test_array.py
This is an xarray workload that apparently is a stereotypical example of workloads that don't run well on dask, see https://github.com/pangeo-data/distributed-array-examples/issues/2
In it's current form, it runs into a lot of spilling and runs for about 2:30min even though it _should_ be an almost embarrassingly parallel reduction. The culprit is dask.order see https://github.com/dask/dask/issues/10384 (I have a bit of a messed up order prototype where this workload runs in ~30s)
I'm not writing this test case as adaptable to cluster size. Mostly because in my experience the automatic scaling functions do not exactly what they are supposed to and I consider the value-add not worth the time tweaking this to get it into the same shape.
=> Add quadratic mean xarray workload

tests/benchmarks/test_dataframe.py
We are removing shuffles now when the length is computed on a DataFrame, so this test is a but pointless for dask_expr. That's the fastest op that should not remove the shuffle.
=> Avoid removing shuffle in shuffle benchmark

tests/benchmarks/test_parquet.py
=> XFAIL test_read_spark_generated_data

AB_environments/AB_baseline.conda.yaml, AB_environments/AB_sample.conda.yaml, ci/environment.yml
- Bump PyArrow to 12 (follow-up to #992)
- Bump dask and distributed to a recent version. Note that, in nightly/PR CI, it's overridden by the git tip.
=> Realign A/B environments to main env

AB_environments/AB_baseline.conda.yaml, AB_environments/AB_sample.conda.yaml, ci/environment.yml
General upgrade of all dependencies.
A/B test [https://github.com/coiled/benchmarks/actions/runs/6262315429] highlights a reduction in runtime in several H2O tests (q1-q7) and no regression anywhere.
- Blocked by and incorporates #1004
=> Bump all dependencies in conda recipe

.github/workflows/tests.yml, ci/environment-test.yml, setup.cfg
Individually fail hung tests and continue. 
Before this, the whole test suite would hang, only to die 2 hours later on the github actions timeout with no indication of which was the offending test.
Known issue: a hung test killed this way won't produce a cluster dump.
=> Add pytest-timeout

tests/benchmarks/test_array.py
This is the example from https://github.com/dask/dask/issues/10384
=> Add xarray reduction from dask#10384 

.github/workflows/ab_tests.yml, .github/workflows/tests.yml, ci/environment-git-tip.yml
- Closes #1000
This workaround was already in elsewhere in the CI script, where it uses the aws cli from the client. No idea why fsspec worked until now and now it stopped.
Tests are still failing due to https://github.com/dask/distributed/pull/8221
Test evidence at https://github.com/coiled/benchmarks/actions/runs/6342421437/job/17228227173
=> Fix access to s3

tests/benchmarks/test_h2o.py
The current implementation generates a test case for all possible defined Datasets. This is not necessary since we can directly just generate those that are enabled.
Either way, if we decide to skip, the skip should be implemented in a fixture further up the DAG. By having `ddf` depend on `small_client`, it will execute `small_client` every time, i.e. it will connect a new client and restart the cluster just to enter `ddf` and decide to skip.
Considering that 6 out of 9 datasets are skipped and there are 9 test cases, this gives us 54 unnecessary client connections + 2 restarts.
This fixes both...
=> Faster skip for H2O tests

tests/workflows/test_pytorch_optuna.py
Will close #1047, close #1048, close #1049, close #1051
Removing the torch pinning also fixes it apparently not running on GPU, which also turns out to close #969; in that issue it was reported that 60 trials were ran, trying again before this fix it was 57; might be some semi-randomness to amount of trials being accomplished when running on CPU(?). Ran twice (and once more here in this PR) and it passes with the expected 50 trials.
=> Fix PyTorch Optuna

tests/benchmarks/tpch/test_dask.py
dask-expr should now be resilient against the sort_values calls. So no need to keep the computes anymore.
=> Remove early computes in tpch benchmarks

alembic/versions/78c6e00fee88_remove_task_based_shuffle.py, tests/benchmarks/test_dataframe.py, tests/benchmarks/test_join.py, tests/runtime/test_cluster_creation.py, tests/runtime/test_coiled.py
I spent ten minutes going through benchmarks and seeing what we could remove.  There were two main approaches things here:
1.  Go through the more expensive tests from a previous run
2.  Go through tests/benchmarks/runtime to see if we actually cared about those
I've removed a few.  This is by no means comprehensive or well thought through.  I'm curious how easy it is for us to make changes here.
=> Clean up and remove a few long tests

alembic/versions/87cbf883c2be_update_tpch_refactor_from_1094.py, alembic/versions/b0e8d5f3295d_update_test_tpch_tpch_test_dask_from_.py
Manually checked this out from the benchmark db on S3; after migration is applied:
=> Add migration for tpch tests restructure from #1094 and #1044

dashboard.py
This reduces the generated files' size from 150 MB to 20 MB and automatically eliminates stale tests from the dashboard.
=> Limit dashboard to last 30 days

ci/environment.yml, cluster_kwargs.yaml, setup.cfg, tests/tpch/conftest.py, tests/tpch/generate_plot.py, tests/tpch/test_dask.py, tests/tpch/test_polars.py, tests/tpch/visualize.ipynb
This does a few things:
1.  Generate performance reports for every query if you add the `--performance-report` flag
2. Generate altair comparison charts
3. Change the infrastructure size up and down based on scale
4. Use Arrow filesystem (although I'm not sure how big a deal this is yet)
5. Improve charts to use consistent coloring, and drop ibis for pandas
=> Update TPCH Infrastructure

tests/tpch/generate-data.py
Propose to add generation of TPC-H data using Coiled when the path is an S3 bucket. 
Edits to generate each step in the scale separately. 
I've ran this for scales 100 and 1000. For reference, the scale 1000 took just 8 minutes with this cluster: https://cloud.coiled.io/clusters/297474/information?account=dask-engineering&tab=Metrics&cpu_variation=Worker+Distribution
The scales generated so far with this are in the `s3://coiled-runtime-ci/tpch/scratch/scale-{100, 1000}` directories. I think this enables us to generate the larger scales pretty easily.
=> Support TPC-H gen on dask/coiled

tests/tpch/test_dask.py
Count is the wrong function for these operations.
According to the spec, we want to get the length of every group. Count does count the rows in every group, but it ignores missing values. The results are the same because the column that we apply count to doesn't have missing values, but this requires knowledge of the data which is not in scope for TPC-H. The thing we actually want is size, which returns the size of every group irrespective of missing values
=> Align TPC-H benchmarks better with their definition

tests/benchmarks/test_parquet.py, tests/benchmarks/test_spill.py, tests/benchmarks/test_work_stealing.py, tests/conftest.py
Lately we've frequently encountered stuck clusters on
```python
cluster.scale(n)
await client.wait_for_workers(n)
```
When that happens, reduce the timeout from 1 hour to 10 minutes.
=> Add timeout to wait_for_workers

tests/benchmarks/test_parquet.py
- xref #998
Not only this test is exceptionally slow, but it also causes the next test to time out on setup, waiting for dead workers.
=> skip test_read_spark_generated_data

tests/tpch/conftest.py
The `dataset_path` fixture didn't fit the paths created by the data generation script. This PR fixes that.
=> Fix local paths for TPC-H data

.github/workflows/tests.yml, AB_environments/config.yaml, setup.cfg, tests/conftest.py, tests/runtime/test_xgboost.py, tests/stability/test_array.py, tests/stability/test_deadlock.py, tests/tpch/README.md, tests/tpch/test_dask.py, tests/tpch/test_duckdb.py, tests/tpch/test_polars.py, tests/tpch/test_pyspark.py, tests/tpch/visualize.ipynb, tests/workflows/test_embarrassingly_parallel.py, tests/workflows/test_from_csv_to_parquet.py, tests/workflows/test_pytorch_optuna.py, tests/workflows/test_snowflake.py, tests/workflows/test_uber_lyft.py, tests/workflows/test_xgboost_optuna.py
Simplify the design for including/excluding tests:
- Manually running `pytest tests`, `pytest tests/tpch`, or `pytest tests/workflow` now runs everything, as expected
- It is now possible to run non-dask TPCH tests and/or workflows in A/B
- When tests are run by default doesn't change. What changes is how easy it is to go against it:
- everything outside of benchmarks is still excluded by default in A/B
- workflows and non-dask TPCH tests still run exclusively overnight, unless explicitly requested through PR tags
Out of scope:
- reduce frequency of non-TPCH tests to weekly
=> A more intuitive design for including/excluding tests

ci/scripts/discover_ab_environments.py
This PR allows, for example, to write in `AB_environments/config.yaml`:
```yaml
targets:
- tests/benchmarks/test_rechunk.py::test_swap_axes[1-128 MiB-tasks]
- tests/benchmarks/test_rechunk.py::test_swap_axes[1-128 MiB-p2p-disk]
- tests/benchmarks/test_rechunk.py::test_tiles_to_rows[1-128 MiB-tasks]
- tests/benchmarks/test_rechunk.py::test_tiles_to_rows[1-128 MiB-p2p-disk]
```
=> Support whitespace in A/B targets

.github/workflows/tests.yml, AB_environments/AB_baseline.conda.yaml, AB_environments/AB_sample.conda.yaml, README.md, ci/environment-tpch-nondask.yml, ci/environment.yml
Non-dask TPCH tests have substantial dependencies that can be very fiddly, and are typically excluded from PRs and A/B tests. Move them out of the way in order to slim down the general environment file and possibly for faster deployment (a crude spot observation shows cluster startup time has gone down from 300s to 230s).
- Blocked by and incorporates #1220
=> Move aside TPCH non-dask dependencies

tests/tpch/test_dask.py
Part of #1274
The result is still wrong but that's a separate issue.
=> Avoid shuffle error in Q10

tests/tpch/test_correctness.py, tests/tpch/test_dask.py
Reverts coiled/benchmarks#1277
can not reproduce locally
=> Revert "[TPC-H] Refactor query 9 to avoid recursion error in dask-expr"

tests/tpch/test_dask.py
Push filtering above merge, removes timeout error for me when running thru Coiled locally. We'll see what CI says.
=> [TPC-H] Query 9 avoid TimeoutError

tests/workflows/test_pytorch_optuna.py
Will close https://github.com/coiled/benchmarks/issues/1261
_"90% of the time, it works every time."_ :wink: 
Mostly works on CI, but occasionally fails because the model doesn't manage to detect/use CUDA. IMO I don't think it's worthwhile to devote much time debugging why this is the case.
=> xfail PyTorch Optuna workflow on TimeoutError

.github/workflows/tests.yml
This PR fixes a bug where matrix elements with the same `os` and `python-version` would generate the same `benchmark.db` with the last uploaded version winning. This explains why Snowflake data is mostly missing.
=> Don't overwrite `benchmark.db` in Action matrix

.github/workflows/tests.yml
We thought that the existing logic worked, but it turns out that we were just running Dask-based TPC-H queries once as part of  `Tests / tests` and then running _all_ TPC-H queries as part of the `Tests / tests/tpch -m tpch_nondask` run and discarding the results of the latter run due to #1332.
=> Limit execution of TPC-H non-Dask benchmarks

tests/tpch/conftest.py, tests/tpch/generate_plot.py
Fixes `ERROR tests/tpch/test_dask.py::test_query_22 - ValueError: invalid literal for int() with base 10: 'optimization[1]'`
=> Fix CI failure

tests/tpch/generate_data.py
I was getting errors running `python tests/tpch/generate_data.py --scale 1` locally (one from `click.Choice` not liking a generator as input, and another due to compression name uppercase/lowercase mismatch). This PR fixes things for me locally.
=> TPC-H data generation script fixup

tests/tpch/conftest.py
Adjusts default cluster sizes following changes suggested in #1166. 
Changes:
**Scale 10**
* Reduced number of VMs by half from 16 to 8 machines. This is probably better as it felt opverprovisioned.
* Halfed single VM size from `m6i.8xlarge` (32 CPUs, 128 GiB RAM) to `m6i.4xlarge` (16 CPUs, 64 GiB RAM) to match.
**Scale 100**
_No changes_
**Scale 1000**
* Doubled VM size form `m6i.large` (2 CPUs, 8 GiB RAM) to `m6i.xlarge` (4 CPUs, 16 GiB RAM).
During our latest runs, we've noticed that the configuration for scale 1000 is not large enough and needs to be doubled. 
* Doubled single VM size from `m6i.16xlarge` (64 CPUs, 256 GiB RAM) to `m6i.32xlarge` (128 CPUs, 256 GiB RAM) to match.
**Scale 10000**
* Reduced number of VMs by half from 64 to 32 to match single VM size. 
_Note: We have not …
=> [TPC-H] Adjust default cluster sizes

tests/tpch/dask_queries.py
Workaround for https://github.com/coiled/benchmarks/issues/1376. In the future, this should be superseded by https://github.com/dask-contrib/dask-expr/issues/867.
=> [TPC-H] Set `split_out=True` in groupby-aggregations in Q11, Q13, Q17 and Q18

.github/workflows/tests.yml
Closes #1383 
Follow-up to https://github.com/coiled/benchmarks/pull/1349 which accidentally caused all tests to be run on Python 3.11. 
FWIW, we didn't lose data but accidentally ran tests on 3.11 and even generated dashboards for that: https://benchmarks.coiled.io/Python%203.11.html
=> Fix python-version argument for benchmarks

tests/tpch/dask_queries.py
The join ordering we chose in query 18 is suboptimal and causes workers run OOM. This PR reimplements the query using Spark's join ordering. Note that Polars join ordering (https://github.com/coiled/benchmarks/commit/8eb24d068401269b665c485b27ee53d8b748da47) appears to be slightly faster (285s vs. 318s), but I do not want to optimize too much manually. Picking Spark's join ordering will provide the best apples-to-apples comparison against Dask's main competitor.
=> [TPC-H] Adopt Spark join ordering in query 18

tests/workflows/test_pytorch_optuna.py
Followup to #1318 which was catching the wrong TimeoutError, should have been asyncio.exceptions.TimeoutError. 
Closes https://github.com/coiled/benchmarks/issues/1402
=> pytorch optuna xfail on correct asyncio TimeoutError

tests/tpch/generate_data.py
Will close #1386
It's made slightly more complex b/c duckdb doesn't support generating data for a single table. So we can keep things mostly the same but just not write out the partitions but collect and combine them at the end of the normal partition generation.
Also made some other adjustments small refactoring, including using a localcluster to generate the data locally to more closely replicate the behavior when using Coiled. Plus it goes faster generating larger scales. :)
=> Refactor TPC-H generation script - consolidate small table partitions

tests/tpch/test_optimization.py
On top of the plain optimization, this measures the time it takes to submit the graph. This is typically the time it takes after hitting compute until the dashboard shows something.
This is likely skewed by caching as introduced in https://github.com/dask-contrib/dask-expr/pull/917 (the fsspec implementation also uses various caching layers) but I still believe this is added value
=> Measure computation submission delay

tests/tpch/dask_queries.py, tests/tpch/test_dask.py, tests/tpch/test_duckdb.py, tests/tpch/test_polars.py, tests/tpch/test_pyspark.py
> FRACTION is chosen as 0.0001 / SF.
according to the TPC-H specs. Not following this causes us to return empty results on larger scale factors.
=> Fix fraction in Q11

tests/tpch/test_duckdb.py
The revenue calculation was numerically unstable and Q15 could (incorrectly) return no results.
=> Fix numerical instability in DuckDB Q15

tests/tpch/dask_queries.py, tests/tpch/test_correctness.py, tests/tpch/test_dask.py, tests/tpch/test_optimization.py
Having a default for Q11 could lead to the scale used for the data and the query diverging. Requiring it for each query avoids special casing.
=> [TPC-H] Require `scale` argument for Dask queries

.github/workflows/tpch.yml
Previously, this would overwrite `PYTEST_BENCHMARKS`.
=> Fix TPC-H workflow

tests/tpch/utils.py
Spark recently ran out of space (https://github.com/coiled/benchmarks/actions/runs/8231277279/job/22506263406#step:8:745). We should bump the disk size.
=> Increase instance disk size for TPC-H SF 1000

tests/conftest.py, tests/tpch/conftest.py, tests/tpch/test_correctness.py
Spans are based on annotations, and annotations don't work with dask-expr.
However this caveat applies only to _nesting_ annotations in the layers - any annotations that are active when you hit compute/persist will be captured.
=> Tag all tests using spans

README.md
Will close #1493 
Given the setting up of TPC-H benchmarking and related information is 'buried' in `tests/tpch`, I think it's useful to have a link to it on the main README.
=> Add link to TPC-H README on main README

AB_environments/README.md
I just wasted another overnight A/B run because of this.
This PR saves 30s when syncing the tags - which is to say, very very frequently. 
Hopefully if the operation is mechanical enough to do it will become automatic for developers.
It would be better to have a pre-commit action but that would take a lot more effort to write.
=> Update README for misaligned git tags

tests/tpch/conftest.py, tests/tpch/generate_plot.py, tests/tpch/test_pyspark.py
This is a follow up from https://github.com/coiled/benchmarks/pull/1490 and supersedes https://github.com/coiled/benchmarks/pull/1492
It also changes the blocking call for spark from `show` to `collect`. Nothing changes really but we won't print the result. I think this is the closest there is to an ordinary `compute`
=> Fix local pyspark for osx

ci/requirements-1tpch-non-dask.in
In case we can/want to rerun polars numbers with https://github.com/coiled/benchmarks/pull/1512 we can also include a more recent version
=> bump polars version

ci/scripts/combine-dbs.sh
This PR truncates the `test_run` table in the `benchmark.db` to the runs of the last 90 days. This reduces the size of the database from ~10 GB to ~500 MB and keeps it at that level. Currently, CI workers are unable to process the existing DB causing CI to fail since June 1st.
We don't truncate `tpch_run` since we don't store `start`.
=> Truncate `test_run` table in `benchmark.db` to the last 90 days

.github/workflows/ab_tests.yml
A/B tests didn't run properly because env variables were out-of-sync between `ab_tests.yml` and `tests.yml`.
=> Fix env variables for AB tests

AB_environments/AB_baseline.conda.yaml, AB_environments/AB_sample.conda.yaml, ci/environment.yml, cluster_kwargs.yaml, tests/benchmarks/test_array.py, tests/benchmarks/test_xarray.py
each query runs around 50s, we are fine with spot-with-fallback since we mostly care about memory pressure
=> Add example for xarray groupby reduction causing memory pressure

.github/workflows/ab_tests.yml, .github/workflows/tests.yml, alembic/versions/2d2405ad763b_drop_tpc_h_data.py, tests/tpch/conftest.py, tests/tpch/dask_queries.py, tests/tpch/duckdb_queries.py, tests/tpch/test_correctness.py, tests/tpch/test_dask.py, tests/tpch/test_duckdb.py, tests/tpch/test_optimization.py, tests/tpch/test_polars.py, tests/tpch/test_pyspark.py
I don't see a point in testing 10 GB workloads. If we're cost-conscious, I'd rather reduce the frequency of testing.
=> Adjust TPC-H testing on CI

AB_environments/config.yaml
By adding this marker by default, we exclude non-Dask TPC-H from A/B tests even if `tests/tpch` is included.
=> Add marker to exclude non-Dask TPC-H tests by default

tests/tpch/conftest.py
This makes sure that `coiled.function` are tagged appropriately.
=> Tag coiled.function in TPC-H

tests/geospatial/test_rechunking.py
This extends our rechunking example to cover multiple dataarrays. This doesn't complete successfully today. 
cc @hendrikmakait  @phofl
=> Add multi-variable rechunking

.github/workflows/tests.yml, tests/geospatial/test_atmospheric_circulation.py
xref https://github.com/coiled/benchmarks/discussions/1545#discussioncomment-10675652
cc @dcherian @hendrikmakait 
EDIT: Here's a run of the "small" version of this test https://cloud.coiled.io/clusters/598243/account/dask-engineering-gcp/information?quick=Just+mine. Takes ~9 minutes and costs ~$0.20
=> Add atmospheric circulation benchmark

tests/geospatial/test_climatology.py
Closes #1549 
This benchmark doesn't even run at the small scale yet.
=> Add benchmark for climatology

AB_environments/AB_baseline.conda.yaml, AB_environments/AB_sample.conda.yaml, ci/environment.yml, tests/geospatial/test_regrid.py
=> Add regridding benchmark

.github/workflows/ab_tests.yml, .github/workflows/tests.yml, .github/workflows/tpch.yml, tests/benchmarks/test_parquet.py, tests/benchmarks/test_spill.py, tests/benchmarks/test_work_stealing.py, tests/benchmarks/test_xarray.py, tests/conftest.py, tests/stability/test_deadlock.py
I don't think it's necessary that we store cluster dumps for every benchmark, so I've removed that functionality.
=> Don't store cluster dumps for benchmarks

AB_environments/AB_baseline.conda.yaml, AB_environments/AB_sample.conda.yaml, ci/environment-test.yml, ci/environment.yml, tests/conftest.py, tests/geospatial/conftest.py, tests/geospatial/test_satellite_filtering.py
xref https://github.com/coiled/benchmarks/issues/1548
=> Add satellite image processing benchmark

tests/conftest.py
"Folders" might not exist in object stores, so let's not fail when that's the case because no file has been added at that location.
=> Fix cleanup of object-store directories

.github/workflows/ab_tests.yml, .github/workflows/tests.yml, .github/workflows/tpch.yml, AB_environments/AB_baseline.conda.yaml, AB_environments/AB_sample.conda.yaml, alembic/versions/1095dfdfc4ae_add_column_for_memray_profiles_url.py, benchmark_schema.py, ci/environment.yml, tests/conftest.py, tests/geospatial/conftest.py
Closes #1567 
Note: This requires tests to be run with the `--benchmark` flag
=> Collect scheduler memray profiles when benchmarking geospatial tests

tests/conftest.py, tests/geospatial/conftest.py
To use this, execute benchmarks with `--benchmark --performance-report`
=> Allow collection of performance reports for geospatial benchmarks

tests/geospatial/test_regrid.py
This uses the full ERA5 dataset with 37 levels and 1h granularity. This matches the annotated data sizes.
=> Use standard dataset in regrid

tests/geospatial/test_regridding.py, tests/geospatial/workloads/regridding.py
For this benchmark, the most interesting scaling dimension is the size of the weight matrix which depends on the output resolution. We should, therefore, scale it along this dimension.
cc @phofl
=> Recalibrate scales of regridding benchmark

.github/workflows/tests.yml, ci/environment-geospatial.yml, ci/environment.yml
`memray` isn't available for Windows. We should also avoid running geospatial benchmarks on the schedule for now.
=> Fix CI run for Windows stability

.github/workflows/tests.yml
PySpark 3.X is not compatible with NumPy 2.X
=> Fix `tests` CI for TPC-H

tests/geospatial/test_cloud_optimize.py, tests/geospatial/workloads/cloud_optimize.py
We can just use simple string paths now (instead of manually opening files) with the latest ``xarray`` release
=> Use string paths with ``open_mfdataset``

cluster_kwargs.yaml, tests/benchmarks/test_work_stealing.py
Closes #1620
Our clusters get created _once_ per module and get shut down after 2 minutes if no client is connected (and after 20 minutes of idleness). Therefore, we should group tests by the cluster fixture to ensure that they are being utilized back-to-back.
We could potentially increase the `no-client-timeout`, but this still won't work if there's a gap of 20 minutes so I'd prefer either sorting within the module or breaking modules apart bhy cluster.
=> Group tests for work-stealing by underlying cluster fixture

.github/workflows/tests.yml
When we last discussed recent CI issues, we agreed that we don't care too much about the stability test, in particular a full test matrix. I still see value in having these tests around, in particular `test_install_plugins`, so I am not removing these entirely. This PR simplifies the test matrix to a single run with a default OS and Python version.
=> Reduce test matrix for stability tests

.github/workflows/tests.yml
Apparently we need to specify _all_ values: https://github.com/coiled/benchmarks/actions/runs/12635100154/workflow
=> Fix tests matrix

AB_environments/AB_baseline.conda.yaml, AB_environments/AB_sample.conda.yaml, AB_environments/README.md, ci/environment-dashboard.yml, ci/environment-git-tip.yml, ci/environment.yml, tests/benchmarks/test_join.py, tests/conftest.py, tests/geospatial/test_climatology.py, tests/tpch/conftest.py, tests/tpch/dask_queries.py, tests/tpch/test_dask.py
Follow-up to https://github.com/dask/dask/pull/11623
Closes https://github.com/coiled/benchmarks/issues/1647
The only thing I haven't purged is the `dask_expr_version` column from the runs.
=> Purge `dask-expr`
